-- =============================================================================
-- SEED: 37 Cornell Duffield Engineering Project Teams
-- Run this in the Supabase SQL Editor after migration 010 has been applied.
--
-- Uses ON CONFLICT (name) DO UPDATE so it safely upserts existing teams
-- (e.g. DTI, Rocketry, AppDev from seed.sql) with logo_url and description.
-- =============================================================================

-- We need a unique constraint on name for ON CONFLICT to work.
-- Add it idempotently:
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'teams_name_key'
  ) THEN
    ALTER TABLE teams ADD CONSTRAINT teams_name_key UNIQUE (name);
  END IF;
END $$;

INSERT INTO teams (name, description, category, website, logo_url, owner_id, custom_questions) VALUES
  ('AguaClara', 'Develops open-source water treatment technologies for communities in Honduras and around the world.', 'Humanitarian', 'https://aguaclara.cornell.edu/', '/team-logos/agua-clara.png', NULL, '[{"id":"q1","label":"Why do you want to join AguaClara?","type":"textarea","required":true},{"id":"q2","label":"Which subteam do you want to join, and why?","type":"textarea","required":true}]'),
  ('Cornell AppDev', 'An engineering project team that builds apps to improve student life at Cornell.', 'Technology', 'https://www.cornellappdev.com/', '/team-logos/appdev.png', NULL, '[{"id":"q1","label":"Why do you want to join Cornell AppDev?","type":"textarea","required":true},{"id":"q2","label":"Which subteam do you want to join, and why?","type":"textarea","required":true}]'),
  ('Cornell Baja Racing', 'Designs and builds an off-road vehicle to compete in the annual Baja SAE competition.', 'Engineering', 'https://baja.mae.cornell.edu/', '/team-logos/baja-racing.png', NULL, '[{"id":"q1","label":"Why do you want to join Cornell Baja Racing?","type":"textarea","required":true},{"id":"q2","label":"Which subteam do you want to join, and why?","type":"textarea","required":true}]'),
  ('C2S2', 'Designs and fabricates custom integrated circuits and ASIC chips.', 'Engineering', 'https://c2s2.engineering.cornell.edu/', '/team-logos/c2s2.png', NULL, '[{"id":"q1","label":"Why do you want to join C2S2?","type":"textarea","required":true},{"id":"q2","label":"Which subteam do you want to join, and why?","type":"textarea","required":true}]'),
  ('Cornell Concrete Canoe', 'Designs, builds, and races a canoe made entirely of concrete for the ASCE competition.', 'Engineering', 'https://cornellconcretecanoe.com/', '/team-logos/concrete-canoe.png', NULL, '[{"id":"q1","label":"Why do you want to join Cornell Concrete Canoe?","type":"textarea","required":true},{"id":"q2","label":"Which subteam do you want to join, and why?","type":"textarea","required":true}]'),
  ('Cornell Data Science', 'A project team dedicated to exploring data science through research, education, and project development.', 'Technology', 'https://cornelldata.science/', '/team-logos/cds.png', NULL, '[{"id":"q1","label":"Why do you want to join Cornell Data Science?","type":"textarea","required":true},{"id":"q2","label":"Which subteam do you want to join, and why?","type":"textarea","required":true}]'),
  ('Cornell Electric Vehicles', 'Builds high-performance electric vehicles including an electric motorcycle and go-kart.', 'Engineering', 'https://www.cornellelectricvehicles.org/', '/team-logos/cev.png', NULL, '[{"id":"q1","label":"Why do you want to join Cornell Electric Vehicles?","type":"textarea","required":true},{"id":"q2","label":"Which subteam do you want to join, and why?","type":"textarea","required":true}]'),
  ('Cornell ChemE Car', 'Designs and builds a chemically powered car to compete in the AIChE Chem-E-Car competition.', 'Engineering', 'https://cornellchemecar.com/', '/team-logos/cheme-car.png', NULL, '[{"id":"q1","label":"Why do you want to join Cornell ChemE Car?","type":"textarea","required":true},{"id":"q2","label":"Which subteam do you want to join, and why?","type":"textarea","required":true}]'),
  ('Cornell Mars Rover', 'Builds a Mars rover prototype to compete in the University Rover Challenge.', 'Engineering', 'https://marsrover.engineering.cornell.edu/', '/team-logos/cmr.png', NULL, '[{"id":"q1","label":"Why do you want to join Cornell Mars Rover?","type":"textarea","required":true},{"id":"q2","label":"Which subteam do you want to join, and why?","type":"textarea","required":true}]'),
  ('Cornell Combat Robotics', 'Designs and builds combat robots for competitions including NHRL events.', 'Engineering', 'https://combatrobotics.engineering.cornell.edu/', '/team-logos/combat-robotics.png', NULL, '[{"id":"q1","label":"Why do you want to join Cornell Combat Robotics?","type":"textarea","required":true},{"id":"q2","label":"Which subteam do you want to join, and why?","type":"textarea","required":true}]'),
  ('Cornell Assistive Technologies', 'Creates assistive technology devices and solutions for people with disabilities.', 'Biomedical', 'https://www.cornellassist.com/', '/team-logos/assistive-tech.png', NULL, '[{"id":"q1","label":"Why do you want to join Cornell Assistive Technologies?","type":"textarea","required":true},{"id":"q2","label":"Which subteam do you want to join, and why?","type":"textarea","required":true}]'),
  ('Cornell Hyperloop', 'Designs and builds a hyperloop pod prototype for the SpaceX Hyperloop Pod Competition.', 'Engineering', 'https://www.cornellhyperloop.com/', '/team-logos/hyperloop.png', NULL, '[{"id":"q1","label":"Why do you want to join Cornell Hyperloop?","type":"textarea","required":true},{"id":"q2","label":"Which subteam do you want to join, and why?","type":"textarea","required":true}]'),
  ('Cornell Rocketry Team', 'Designs, builds, and launches high-powered rockets to compete in the Spaceport America Cup.', 'Engineering', 'https://cornellrocketryteam.com/', '/team-logos/crt.png', NULL, '[{"id":"q1","label":"Why do you want to join Cornell Rocketry Team?","type":"textarea","required":true},{"id":"q2","label":"Which subteam do you want to join, and why?","type":"textarea","required":true}]'),
  ('Cornell Cup Robotics', 'Develops precision robotic systems and automation solutions.', 'Engineering', 'https://www.cornellcuprobotics.com/', '/team-logos/cup-robotics.svg', NULL, '[{"id":"q1","label":"Why do you want to join CUP Robotics?","type":"textarea","required":true},{"id":"q2","label":"Which subteam do you want to join, and why?","type":"textarea","required":true}]'),
  ('CUAD', 'Builds autonomous drones for the IARC competition.', 'Engineering', 'https://cuad.info/', '/team-logos/cuad.png', NULL, '[{"id":"q1","label":"Why do you want to join CUAD?","type":"textarea","required":true},{"id":"q2","label":"Which subteam do you want to join, and why?","type":"textarea","required":true}]'),
  ('CUAir', 'Designs autonomous aerial vehicles for search and rescue missions.', 'Engineering', 'https://cuair.org/', '/team-logos/cu-air.png', NULL, '[{"id":"q1","label":"Why do you want to join CU-AIR?","type":"textarea","required":true},{"id":"q2","label":"Which subteam do you want to join, and why?","type":"textarea","required":true}]'),
  ('CU Autoboat', 'Builds autonomous surface vessels to compete in the RoboBoat competition.', 'Engineering', 'https://www.cornellautoboat.com/', '/team-logos/cu-autoboat.jpg', NULL, '[{"id":"q1","label":"Why do you want to join CU Autoboat?","type":"textarea","required":true},{"id":"q2","label":"Which subteam do you want to join, and why?","type":"textarea","required":true}]'),
  ('CU AUV', 'Builds AUVs for the RoboSub competition.', 'Engineering', 'https://cuauv.org/', '/team-logos/cu-auv.png', NULL, '[{"id":"q1","label":"Why do you want to join CU AUV?","type":"textarea","required":true},{"id":"q2","label":"Which subteam do you want to join, and why?","type":"textarea","required":true}]'),
  ('CUBMD', 'Designs and prototypes medical devices to address clinical needs.', 'Biomedical', 'https://www.cubmd.org/', '/team-logos/cubmd.png', NULL, '[{"id":"q1","label":"Why do you want to join CUBMD?","type":"textarea","required":true},{"id":"q2","label":"Which subteam do you want to join, and why?","type":"textarea","required":true}]'),
  ('CU Geo Data', 'Applies geospatial data science and remote sensing to solve environmental and infrastructure challenges.', 'Engineering', 'https://www.cugeodata.com/', '/team-logos/cu-geo-data.png', NULL, '[{"id":"q1","label":"Why do you want to join CU Geo Data?","type":"textarea","required":true},{"id":"q2","label":"Which subteam do you want to join, and why?","type":"textarea","required":true}]'),
  ('CU Sail', 'Designs and builds autonomous sailing robots for the International Robotic Sailing Regatta.', 'Engineering', 'https://cusail.com/', '/team-logos/cu-sail.png', NULL, '[{"id":"q1","label":"Why do you want to join CU Sail?","type":"textarea","required":true},{"id":"q2","label":"Which subteam do you want to join, and why?","type":"textarea","required":true}]'),
  ('CUXRL', 'Develops VR, AR, and XR applications and research projects.', 'Technology', 'https://cornellxr.com/', '/team-logos/cuxrl.png', NULL, '[{"id":"q1","label":"Why do you want to join CUXRL?","type":"textarea","required":true},{"id":"q2","label":"Which subteam do you want to join, and why?","type":"textarea","required":true}]'),
  ('DEBUT', 'Creates biomedical devices for the BMES DEBUT competition.', 'Biomedical', 'https://cornelldebut.org/', '/team-logos/debut.png', NULL, '[{"id":"q1","label":"Why do you want to join DEBUT?","type":"textarea","required":true},{"id":"q2","label":"Which subteam do you want to join, and why?","type":"textarea","required":true}]'),
  ('Cornell Design Build Fly', 'Designs and builds remote-controlled aircraft for the AIAA Design/Build/Fly competition.', 'Engineering', 'https://dbf.engineering.cornell.edu/', '/team-logos/design-build-fly.png', NULL, '[{"id":"q1","label":"Why do you want to join Cornell Design Build Fly?","type":"textarea","required":true},{"id":"q2","label":"Which subteam do you want to join, and why?","type":"textarea","required":true}]'),
  ('Cornell DTI', 'Builds products to improve the lives of those in the Cornell community.', 'Technology', 'https://new.cornelldti.org/', '/team-logos/dti.png', NULL, '[{"id":"q1","label":"Why do you want to join Cornell DTI?","type":"textarea","required":true},{"id":"q2","label":"Which subteam do you want to join, and why?","type":"textarea","required":true}]'),
  ('Engineers in Action', 'Designs and builds pedestrian bridges for isolated communities in developing countries.', 'Humanitarian', 'https://eia.engineering.cornell.edu/', '/team-logos/engineers-in-action.jpg', NULL, '[{"id":"q1","label":"Why do you want to join Engineers in Action?","type":"textarea","required":true},{"id":"q2","label":"Which subteam do you want to join, and why?","type":"textarea","required":true}]'),
  ('Engineers Without Borders', 'Partners with disadvantaged communities to improve their quality of life through sustainable engineering projects.', 'Humanitarian', 'https://www.ewbcornell.org/', '/team-logos/ewb.png', NULL, '[{"id":"q1","label":"Why do you want to join Engineers Without Borders?","type":"textarea","required":true},{"id":"q2","label":"Which subteam do you want to join, and why?","type":"textarea","required":true}]'),
  ('ESW', 'Works on sustainability-focused engineering projects on campus and beyond.', 'Sustainability', 'https://esw.engineering.cornell.edu/', '/team-logos/esw.png', NULL, '[{"id":"q1","label":"Why do you want to join ESW?","type":"textarea","required":true},{"id":"q2","label":"Which subteam do you want to join, and why?","type":"textarea","required":true}]'),
  ('EWH', 'Designs low-cost medical devices for hospitals in developing countries.', 'Biomedical', 'https://www.cornellewh.org/', '/team-logos/ewh.png', NULL, '[{"id":"q1","label":"Why do you want to join EWH?","type":"textarea","required":true},{"id":"q2","label":"Which subteam do you want to join, and why?","type":"textarea","required":true}]'),
  ('Cornell FSAE Racing', 'Designs and builds a formula-style race car to compete in the Formula SAE competition.', 'Engineering', 'https://cornellracing.org/', '/team-logos/fsae.png', NULL, '[{"id":"q1","label":"Why do you want to join Cornell FSAE Racing?","type":"textarea","required":true},{"id":"q2","label":"Which subteam do you want to join, and why?","type":"textarea","required":true}]'),
  ('Hack4Impact', 'Builds software products pro bono for nonprofits and social impact organizations.', 'Technology', 'https://www.cornellh4i.org/', '/team-logos/hack4impact.png', NULL, '[{"id":"q1","label":"Why do you want to join Hack4Impact?","type":"textarea","required":true},{"id":"q2","label":"Which subteam do you want to join, and why?","type":"textarea","required":true}]'),
  ('Cornell iGEM', 'Conducts synthetic biology research for the iGEM competition.', 'Engineering', 'https://igem.engineering.cornell.edu/', '/team-logos/igem.png', NULL, '[{"id":"q1","label":"Why do you want to join Cornell iGEM?","type":"textarea","required":true},{"id":"q2","label":"Which subteam do you want to join, and why?","type":"textarea","required":true}]'),
  ('Nexus', 'Focuses on sustainable design and campus sustainability initiatives at Cornell.', 'Sustainability', 'https://www.cornellnexus.com/', '/team-logos/nexus.png', NULL, '[{"id":"q1","label":"Why do you want to join Nexus?","type":"textarea","required":true},{"id":"q2","label":"Which subteam do you want to join, and why?","type":"textarea","required":true}]'),
  ('Cornell Seismic Design', 'Designs and builds model structures to withstand simulated earthquakes in the EERI Seismic Design Competition.', 'Engineering', 'https://www.cornellseismicdesign.com/', '/team-logos/seismic-design.png', NULL, '[{"id":"q1","label":"Why do you want to join Cornell Seismic Design?","type":"textarea","required":true},{"id":"q2","label":"Which subteam do you want to join, and why?","type":"textarea","required":true}]'),
  ('Sens Tech', 'Develops wearable sensing technologies and assistive devices for people with visual impairments.', 'Biomedical', 'https://www.cornellsenstech.com/', '/team-logos/sens-tech.jpg', NULL, '[{"id":"q1","label":"Why do you want to join Sens Tech?","type":"textarea","required":true},{"id":"q2","label":"Which subteam do you want to join, and why?","type":"textarea","required":true}]'),
  ('Cornell Solar Boat', 'Designs and builds a solar-powered boat for the Solar Splash competition.', 'Engineering', 'https://cusb.engineering.cornell.edu/', '/team-logos/solar-boat.png', NULL, '[{"id":"q1","label":"Why do you want to join Cornell Solar Boat?","type":"textarea","required":true},{"id":"q2","label":"Which subteam do you want to join, and why?","type":"textarea","required":true}]'),
  ('Cornell Steel Bridge', 'Designs, fabricates, and assembles a steel bridge for the ASCE Steel Bridge Competition.', 'Engineering', 'https://steelbridge.engineering.cornell.edu/', '/team-logos/steel-bridge.png', NULL, '[{"id":"q1","label":"Why do you want to join Cornell Steel Bridge?","type":"textarea","required":true},{"id":"q2","label":"Which subteam do you want to join, and why?","type":"textarea","required":true}]')
ON CONFLICT (name) DO UPDATE SET
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  website = EXCLUDED.website,
  logo_url = EXCLUDED.logo_url,
  custom_questions = EXCLUDED.custom_questions;
